version: "3.7"

services:
  server:
    image: gitea/gitea:1.17.3
    container_name: gitea
    restart: always
    networks: 
      backend:
        aliases:
          - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres
      - GITEA__database__NAME=${DB_NAME}
      - GITEA__database__USER=${DB_USER}
      - GITEA__database__PASSWD=${DB_PASS}
      - GITEA__server__ROOT_URL=https://${HOSTNAME}
      - GITEA__server__SSH_PORT=${SSH_PORT}
      - GITEA__service__DISABLE_REGISTRATION=true
    depends_on: 
      - postgres
  
  postgres:
    image: postgres:14-alpine
    restart: always
    networks: 
      - backend
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-gitea:/var/lib/postgresql/data

networks:
  backend:
    external: true

volumes:
  gitea:
    external: true
  postgres-gitea:
    external: true
